// Generated by Flexc++ V1.08.00 on Mon, 15 Sep 2014 11:50:50 +0800

#include <iostream>
#include <fstream>
#include <sstream>
#include <stdexcept>

// $insert class_ih
#include "HTTPScanner.ih"


    // s_ranges__: use (unsigned) characters as index to obtain
    //           that character's range-number.
    //           The range for EOF is defined in a constant in the
    //           class header file
size_t const HTTPScannerBase::s_ranges__[] =
{
     0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 3, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
     5, 5, 5, 5, 5, 5, 5, 6, 7, 8, 9, 9, 9, 9,10,11,11,11,11,11,12,13,14,15,15,
    15,15,15,15,15,15,15,15,16,17,18,19,20,21,21,21,21,21,21,21,21,21,21,21,21,
    21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,22,22,22,
    22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,23,23,
    23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,
    23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,
    23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,
    23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,
    23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,
    23,23,23,23,23,24,
};

    // s_dfa__ contains the rows of *all* DFAs ordered by start state.
    // The enum class StartCondition__ is defined in the baseclass header
    // INITIAL is always 0.
    // Each entry defines the row to transit to if the column's
    // character range was sensed. Row numbers are relative to the
    // used DFA and d_dfaBase__ is set to the first row of the subset to use.
    // The row's final two values are begin and end indices in
    // s_rfc__[] (rule, flags and count), defining the state's rule details
int const HTTPScannerBase::s_dfa__[][28] =
{
    // INITIAL
    {-1, 1, 2, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 5, 1, 1, 1, 1,
          1, 1, 4, 1, 1,-1,   0, 0},  // 0
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,   0, 1},  // 1
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,   1, 2},  // 2
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,   2, 3},  // 3
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 4, 4, 4,-1,-1,-1,-1,
         -1,-1, 4,-1,-1,-1,   3, 4},  // 4
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 4, 4, 5,-1,-1,-1,-1,
         -1,-1, 4,-1,-1,-1,   4, 5},  // 5
    // tag_attvalue_href
    {-1, 1,-1, 2, 2, 2, 1, 2, 3, 2, 4, 2, 2, 2, 2, 5, 2, 2, 2, 6,
          7, 2, 8, 2, 2,-1,   5, 6},  // 0
    {-1, 1,-1,-1,-1,-1, 1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,   6, 7},  // 1
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,   7, 8},  // 2
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,   8, 9},  // 3
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,   9,10},  // 4
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,  10,11},  // 5
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,  11,12},  // 6
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,  12,13},  // 7
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 8,-1,-1,-1,-1,
         -1,-1, 8,-1,-1,-1,  13,14},  // 8
    // tag_attvalue
    {-1, 1, 2, 2, 2, 2, 1, 2, 3, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          5, 2, 2, 2,-1,-1,  14,15},  // 0
    {-1, 1,-1,-1,-1,-1, 1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,  15,16},  // 1
    {-1,-1, 2, 2, 2, 2,-1, 2,-1, 2,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1, 2, 2, 2,-1,-1,  16,17},  // 2
    {-1, 3, 3, 3, 3, 3, 3, 3, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
          3, 3, 3, 3,-1,-1,  17,17},  // 3
    {-1, 4, 4, 4, 4, 4, 4, 4, 4, 4, 7, 4, 4, 4, 4, 4, 4, 4, 4, 4,
          4, 4, 4, 4,-1,-1,  17,17},  // 4
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,  17,18},  // 5
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,  18,19},  // 6
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,  19,20},  // 7
    // tag_att
    {-1, 1,-1,-1,-1,-1, 1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 2,
          3,-1, 4,-1,-1,-1,  20,21},  // 0
    {-1, 1,-1,-1,-1,-1, 1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,  21,22},  // 1
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,  22,23},  // 2
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,  23,24},  // 3
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 4,-1,-1,-1,-1,
         -1,-1, 4,-1,-1,-1,  24,25},  // 4
    // tag_start
    {-1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1,
          1, 1, 3, 1,-1,-1,  25,25},  // 0
    {-1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          4, 1, 1, 1,-1,-1,  25,26},  // 1
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,  26,27},  // 2
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 3,-1,-1,-1,-1,
         -1,-1, 3,-1,-1,-1,  27,28},  // 3
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,  28,29},  // 4
    // body
    {-1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1,
          1, 1, 1, 1, 1,-1,  29,29},  // 0
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,  29,30},  // 1
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,  30,31},  // 2
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,  31,32},  // 3
    // header
    {-1, 1, 2, 3, 4, 3, 1, 3, 3, 3, 3, 3, 5, 3, 3, 3, 6, 3, 3, 3,
          3, 3, 5, 3,-1,-1,  32,33},  // 0
    {-1, 1,-1,-1,-1,-1, 1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,  33,34},  // 1
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,  34,36},  // 2
    {-1, 3,-1, 3,-1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
          3, 3, 3, 3,-1,-1,  36,37},  // 3
    {-1,-1, 7,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,  37,38},  // 4
    {-1, 3,-1, 3,-1, 3, 3, 3, 3, 3, 3, 3, 5, 3, 3, 3, 3, 3, 3, 3,
          3, 3, 5, 3,-1,-1,  38,40},  // 5
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,  40,41},  // 6
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,  41,42},  // 7
};

    // The first value is the rule index
    // The second value is the FLAG: see the scannerbase.h file
    // 1: Final     4: Count        11: Final/BOL,Inc     
    // 2: Inc.      5: Final,Count  13: Final/BOL,Count
    // 3: Final,Inc 9: Final/BOL    
    // The third value is the LOP count value (valid for Count flags)
size_t const HTTPScannerBase::s_rfc__[][3] =
{
//     R  F  C
     { 4, 1, 0},  // 0
     { 2, 1, 0},  // 1
     { 3, 1, 0},  // 2
     { 1, 1, 0},  // 3
     { 0, 1, 0},  // 4
     {29, 1, 0},  // 5
     {29, 1, 0},  // 6
     {35, 1, 0},  // 7
     {31, 1, 0},  // 8
     {30, 1, 0},  // 9
     {33, 1, 0},  // 10
     {28, 1, 0},  // 11
     {34, 1, 0},  // 12
     {32, 1, 0},  // 13
     {27, 1, 0},  // 14
     {27, 1, 0},  // 15
     {23, 1, 0},  // 16
     {26, 1, 0},  // 17
     {25, 1, 0},  // 18
     {24, 1, 0},  // 19
     {22, 1, 0},  // 20
     {22, 1, 0},  // 21
     {21, 1, 0},  // 22
     {20, 1, 0},  // 23
     {19, 1, 0},  // 24
     {18, 1, 0},  // 25
     {16, 1, 0},  // 26
     {17, 1, 0},  // 27
     {18, 1, 0},  // 28
     {15, 1, 0},  // 29
     {14, 1, 0},  // 30
     {13, 1, 0},  // 31
     { 9, 1, 0},  // 32
     { 9, 1, 0},  // 33
     { 6, 9, 0},  // 34
     {11, 1, 0},  // 35
     {10, 1, 0},  // 36
     {12, 1, 0},  // 37
     { 7, 9, 0},  // 38
     {10, 1, 0},  // 39
     { 8, 1, 0},  // 40
     { 5, 9, 0},  // 41
};

int const (*HTTPScannerBase::s_dfaBase__[])[28] =
{
    s_dfa__ + 0,
    s_dfa__ + 6,
    s_dfa__ + 15,
    s_dfa__ + 23,
    s_dfa__ + 28,
    s_dfa__ + 33,
    s_dfa__ + 37,
};

size_t HTTPScannerBase::s_istreamNr = 0;

// $insert inputImplementation
#include "input.hpp"

HTTPScannerBase::HTTPScannerBase(std::istream &in, std::ostream &out)
:
    d_filename("-"),
    d_startCondition(StartCondition__::INITIAL),
    d_state(0),
    d_out(new std::ostream(out.rdbuf())),
    d_sawEOF(false),
    d_atBOL(true),
    d_tailCount(36, std::numeric_limits<size_t>::max()),
// $insert interactiveInit
    d_in(0),
    d_input(new std::istream(in.rdbuf())),
    d_dfaBase__(s_dfa__)
{}

void HTTPScannerBase::switchStream__(std::istream &in, size_t lineNr)
{
    d_input.close();
    d_state = 0;
    d_input = Input(new std::istream(in.rdbuf()), lineNr);
    d_sawEOF = false;
    d_atBOL = true;
}


HTTPScannerBase::HTTPScannerBase(std::string const &infilename, std::string const &outfilename)
:
    d_filename(infilename),
    d_startCondition(StartCondition__::INITIAL),
    d_state(0),
    d_out(outfilename == "-"    ? new std::ostream(std::cout.rdbuf()) :
          outfilename == ""     ? new std::ostream(std::cerr.rdbuf()) :
                                  new std::ofstream(outfilename)),
    d_sawEOF(false),
    d_atBOL(true),
    d_tailCount(36, std::numeric_limits<size_t>::max()),
    d_input(new std::ifstream(infilename)),
    d_dfaBase__(s_dfa__)
{}

void HTTPScannerBase::switchStreams(std::istream &in, std::ostream &out)
{
    switchStream__(in, 1);
    switchOstream(out);
}


void HTTPScannerBase::switchOstream(std::ostream &out)
{
    *d_out << std::flush;
    d_out.reset(new std::ostream(out.rdbuf()));
}

// $insert debugFunctions
void HTTPScannerBase::setDebug(bool onOff)
{}

bool HTTPScannerBase::debug() const
{
    return false;
}

void HTTPScannerBase::redo(size_t nChars)
{
    size_t from = nChars >= length() ? 0 : length() - nChars;
    d_input.reRead(d_matched, from);
    d_matched.resize(from);
}

void HTTPScannerBase::switchOstream(std::string const &outfilename)
{
    *d_out << std::flush;
    d_out.reset(
            outfilename == "-"    ? new std::ostream(std::cout.rdbuf()) :
            outfilename == ""     ? new std::ostream(std::cerr.rdbuf()) :
                                    new std::ofstream(outfilename));
}


void HTTPScannerBase::switchIstream(std::string const &infilename)
{
    d_input.close();
    d_filename = infilename;
    d_input = Input(new std::ifstream(infilename));
    d_sawEOF = false;
    d_atBOL = true;
}

void HTTPScannerBase::switchStreams(std::string const &infilename,
                           std::string const &outfilename)
{
    switchOstream(outfilename);
    switchIstream(infilename);
}

void HTTPScannerBase::pushStream(std::istream  &istr)
{
    std::istream *streamPtr = new std::istream(istr.rdbuf());
    p_pushStream("(istream)", streamPtr);
}

void HTTPScannerBase::pushStream(std::string const &name)
{
    std::istream *streamPtr = new std::ifstream(name);
    if (!*streamPtr)
    {
        delete streamPtr;
        throw std::runtime_error("Cannot read " + name);
    }
    p_pushStream(name, streamPtr);
}


void HTTPScannerBase::p_pushStream(std::string const &name, std::istream *streamPtr)
{
    if (d_streamStack.size() == s_maxSizeofStreamStack__)
    {
        delete streamPtr;
        throw std::length_error("Max stream stack size exceeded");
    }

    d_streamStack.push_back(StreamStruct{d_filename, d_input});
    d_filename = name;
    d_input = Input(streamPtr);
    d_sawEOF = false;
    d_atBOL = true;
}


bool HTTPScannerBase::popStream()
{
    d_input.close();

    if (d_streamStack.empty())
        return false;

    StreamStruct &top = d_streamStack.back();

    d_input =   top.pushedInput;
    d_filename = top.pushedName;
    d_streamStack.pop_back();
    d_sawEOF = false;

    return true;
}

HTTPScannerBase::ActionType__ HTTPScannerBase::actionType__(size_t range)
{
    d_nextState = d_dfaBase__[d_state][range];

    if (d_nextState != -1)                  // transition is possible
        return ActionType__::CONTINUE;

    if (atFinalState())                     // FINAL state reached
        return ActionType__::MATCH;

    if (d_matched.size())
        return ActionType__::ECHO_FIRST;    // no match, echo the 1st char

    return range != s_rangeOfEOF__ ? 
                ActionType__::ECHO_CH 
            : 
                ActionType__::RETURN;
}

void HTTPScannerBase::accept(size_t nChars)          // old name: less
{
    if (nChars < d_matched.size())
    {
        d_input.reRead(d_matched, nChars);
        d_matched.resize(nChars);
    }
}

  // The size of d_matched is determined:
  //    The current state is a known final state (as determined by 
  // inspectRFCs__(), just prior to calling matched__). 
  //    The contents of d_matched are reduced to d_final's size or (if set)
  // to the LOP-rule's tail size.
void HTTPScannerBase::determineMatchedSize(FinData const &final)
{
    size_t length = final.matchLen;
    if (final.tailCount != std::numeric_limits<size_t>::max())
        length -= final.tailCount;

    d_input.reRead(d_matched, length);      // reread the tail section
    d_matched.resize(length);               // return what's left
}

  // At this point a rule has been matched.  The next character is not part of
  // the matched rule and is sent back to the input.  The final match length
  // is determined, the index of the matched rule is determined, and then
  // d_atBOL is updated. Finally the rule index is returned.
size_t HTTPScannerBase::matched__(size_t ch)
{
    d_input.reRead(ch);

    if (!d_atBOL)
        d_final.atBOL.rule = std::numeric_limits<size_t>::max();

    FinData &final = d_final.atBOL.rule == std::numeric_limits<size_t>::max() ? 
                            d_final.notAtBOL
                        :
                            d_final.atBOL;

    determineMatchedSize(final);

    d_atBOL = *d_matched.rbegin() == '\n';


    return final.rule;
}

size_t HTTPScannerBase::getRange__(int ch)       // using int to prevent casts
{
    if (ch != AT_EOF)
        d_sawEOF = false;

// $insert caseCheck
    ch = tolower(ch);

    return ch == AT_EOF ? static_cast<size_t>(s_rangeOfEOF__) : s_ranges__[ch];
}

  // At this point d_nextState contains the next state and continuation is
  // possible. The just read char. is appended to d_match, and LOP counts
  // are updated.
void HTTPScannerBase::continue__(int ch)
{
    d_state = d_nextState;

    if (ch != AT_EOF)
        d_matched += ch;
}

void HTTPScannerBase::echoCh__(size_t ch)
{
    *d_out << static_cast<char>(ch);
    d_atBOL = ch == '\n';
}


   // At this point there is no continuation. The last character is
   // pushed back into the input stream as well as all but the first char. in
   // the buffer. The first char. in the buffer is echoed to stderr. 
   // If there isn't any 1st char yet then the current char doesn't fit any
   // rules and that char is then echoed
void HTTPScannerBase::echoFirst__(size_t ch)
{
    d_input.reRead(ch);
    d_input.reRead(d_matched, 1);
    echoCh__(d_matched[0]);
}

    // Inspect all s_rfc__ elements associated with the current state
    //  If the s_rfc__ element has its COUNT flag set then set the 
    // d_tailCount[rule] value to the element's tailCount value, if it has its 
    // INCREMENT flag set then increment d_tailCount[rule]
    //  If neither was set set the d_tailCount[rule] to numeric_limits<size_t>::max()
    // 
    // If the s_rfc__ element has its FINAL flag set then store the rule number
    // in d_final.second. If it has its FINAL + BOL flags set then store the
    // rule number in d_final.first
void HTTPScannerBase::inspectRFCs__()
{
    for 
    (
        size_t begin = d_dfaBase__[d_state][s_finacIdx__], 
                 end = d_dfaBase__[d_state][s_finacIdx__ + 1];
            begin != end;
                ++begin
    )
    {
        size_t const *rfc = s_rfc__[begin];
        size_t flag = rfc[FLAGS];
        size_t rule = rfc[RULE];

        if (flag & INCREMENT)
            ++d_tailCount[rule];
        else 
            d_tailCount[rule] = (flag & COUNT) ? rfc[ACCCOUNT] : std::numeric_limits<size_t>::max();

        if (flag & FINAL)
        {
            FinData &final = (flag & BOL) ? d_final.atBOL : d_final.notAtBOL;
            final = FinData { rule, d_matched.size(), d_tailCount[rule] };
        }
    }
}

void HTTPScannerBase::reset__()
{
    d_final = Final { {std::numeric_limits<size_t>::max(), std::numeric_limits<size_t>::max(), std::numeric_limits<size_t>::max() }, 
                      {std::numeric_limits<size_t>::max(), std::numeric_limits<size_t>::max(), std::numeric_limits<size_t>::max() } };
    d_state = 0;
    d_return = true;

    if (!d_more)
        d_matched.clear();

    d_more = false;
}

int HTTPScanner::executeAction__(size_t ruleIdx)
try
{
    switch (ruleIdx)
    {
        // $insert actions
        case 0:
        {
#line 8 "lexer"
            return HTTPParser::INTEGER;

        }
        break;
        case 1:
        {
#line 9 "lexer"
            return HTTPParser::STATUS_IDENT;

        }
        break;
        case 2:
        {
#line 10 "lexer"
            {begin(StartCondition__::header); return matched()[0]; }

        }
        break;
        case 5:
        {
#line 16 "lexer"
            begin(StartCondition__::body); return matched()[1];

        }
        break;
        case 6:
        {
#line 17 "lexer"
            begin(StartCondition__::body); return matched()[0];

        }
        break;
        case 7:
        {
#line 18 "lexer"
            return HTTPParser::HEADER_IDENT;

        }
        break;
        case 8:
        {
#line 19 "lexer"
            return matched()[0];

        }
        break;
        case 10:
        {
#line 21 "lexer"
            return HTTPParser::HEADER_VALUE;

        }
        break;
        case 11:
        {
#line 22 "lexer"
            return matched()[0];

        }
        break;
        case 13:
        {
#line 27 "lexer"
            begin(StartCondition__::tag_start);return matched()[0];

        }
        break;
        case 16:
        {
#line 33 "lexer"
            return matched()[0];

        }
        break;
        case 17:
        {
#line 34 "lexer"
            begin(StartCondition__::tag_att);return HTTPParser::TAG_IDENT;

        }
        break;
        case 18:
        {
#line 35 "lexer"
            begin(StartCondition__::body);return HTTPParser::TAG_IGNORE;

        }
        break;
        case 19:
        {
#line 39 "lexer"
            {
    if (matched()=="href") {
        begin(StartCondition__::tag_attvalue_href);
        return HTTPParser::TAG_IDENT_HREF;
    }
    return HTTPParser::TAG_IDENT;
}

        }
        break;
        case 20:
        {
#line 46 "lexer"
            begin(StartCondition__::body);return matched()[0];

        }
        break;
        case 21:
        {
#line 47 "lexer"
            begin(StartCondition__::tag_attvalue);return matched()[0];

        }
        break;
        case 23:
        case 24:
        case 25:
        {
#line 54 "lexer"
            begin(StartCondition__::tag_att);return HTTPParser::ATT_VALUE;

        }
        break;
        case 26:
        {
#line 55 "lexer"
            begin(StartCondition__::body);return matched()[0];

        }
        break;
        case 28:
        {
#line 59 "lexer"
            urlFirst=true;inURL=false;return matched()[0];

        }
        break;
        case 29:
        {
#line 60 "lexer"
            if(inURL){inURL=false;begin(StartCondition__::tag_att);}

        }
        break;
        case 30:
        case 31:
        {
#line 62 "lexer"
            if(!inURL)inURL=true;else{inURL=false;begin(StartCondition__::tag_att);}

        }
        break;
        case 32:
        {
#line 63 "lexer"
            {
    if (urlFirst) {
        urlFirst=false;
        return HTTPParser::URL_NAME;
    }
    return HTTPParser::URL_IDENT;
}

        }
        break;
        case 33:
        {
#line 70 "lexer"
            urlFirst=false;return HTTPParser::INTEGER;

        }
        break;
        case 34:
        {
#line 71 "lexer"
            begin(StartCondition__::body);return matched()[0];

        }
        break;
        case 35:
        {
#line 72 "lexer"
            urlFirst=false;return matched()[0];

        }
        break;
    }
    noReturn__();
    return 0;
}
catch (Leave__ value)
{
    return static_cast<int>(value);
}

int HTTPScanner::lex__()
{
    reset__();
    preCode();

    while (true)
    {
        size_t ch = get__();                // fetch next char
        size_t range = getRange__(ch);      // determine the range

        inspectRFCs__();                    // update d_tailCount values

        switch (actionType__(range))        // determine the action
        {
            case ActionType__::CONTINUE:
                continue__(ch);
            continue;

            case ActionType__::MATCH:
            {
                d_token__ = executeAction__(matched__(ch));
                if (return__())
                {
                    print();
                    postCode(PostEnum__::RETURN);
                    return d_token__;
                }
                break;
            }

            case ActionType__::ECHO_FIRST:
                echoFirst__(ch);
            break;

            case ActionType__::ECHO_CH:
                echoCh__(ch);
            break;

            case ActionType__::RETURN:
                if (!popStream())
                {
                     postCode(PostEnum__::END);
                     return 0;
                }
                postCode(PostEnum__::POP);
             continue;
        } // switch

        postCode(PostEnum__::WIP);

        reset__();
        preCode();
    } // while
}

void HTTPScannerBase::print__() const
{
}


